### ISSUE TITLE
caret pos after change

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_git_conflict#3]
doc
```
$ cat merge.txt
<<<<<<< HEAD
this is some content to mess with
content to append
=======
totally different content to merge later
>>>>>>> new_branch_to_merge_later

$ cat merge.txt
<<<<<<< HEAD
this is some content to mess with
content to append
=======
totally different content to merge later
>>>>>>> new_branch_to_merge_later

$ cat merge.txt
<<<<<<< HEAD
this is some content to mess with
content to append
=======
totally different content to merge later
>>>>>>> new_branch_to_merge_later
```

scroll to end so 3rd is visible. place caret on `>>>>>` line.
choose 'imcoming'.
==> caret pos broken
![Screenshot from 2021-07-09 18-07-46](https://user-images.githubusercontent.com/4154978/125099467-b5a94e80-e0e0-11eb-8f2a-dc07bacf503a.png)

**Comment by Alexey-T** [comment]
ops, it's ok

**Comment by Alexey-T** [comment]
reopened.

**Comment by halfbrained** [comment]
Fixed.

(tried to save selection in several ways, failed, then realized I can restore carets before manipulating text :D )
