### ISSUE TITLE
When called on clean file, must show some statusbar msg like "No Git conflict found"

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_git_conflict#6]

**Comment by halfbrained** [comment]
https://github.com/halfbrained/cuda_git_conflict/blob/08648da9ab77f1586fc4c42d0be051e369d57a3b/__init__.py#L43-L44

It does, but the message is hidden immediately for some reason. Probably not plugin's fault, should I make a repro plugin?

**Comment by Alexey-T** [comment]
yes, please, it's strange

**Comment by halfbrained** [comment]
Seems to actually work on latest beta and release, so I'm closing
