### ISSUE TITLE
Choosing appropriate dialog height

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_git_conflict#7]
@Alexey-T Will this work as universal `dlg_menu` height here?

``` python
DLG_H = 2*app_proc(PROC_GET_GUI_HEIGHT, 'edit') \
        + 3*app_proc(PROC_GET_GUI_HEIGHT, 'label')
```

![dlg](https://user-images.githubusercontent.com/74829192/125154329-33fa0500-e162-11eb-9759-55f527c1f266.png)

**Comment by Alexey-T** [comment]
not sure it will be the same on Win32 (devs made the change to Height, so that it takes OS_frame).

**Comment by Alexey-T** [comment]
IDE has 'Height' and 'ClientHeight', Cud gives API for 'Height'..

**Comment by halfbrained** [comment]
That's unfortunate 

![wincrap](https://user-images.githubusercontent.com/74829192/125163193-b3083100-e194-11eb-9b30-18f4cee486c4.png)


will leave as is
