### ISSUE TITLE
set caret to start of current conflict

### ISSUE THREAD

**Issue by veksha** [halfbrained/cuda_git_conflict#9]
@Alexey-T

we can add new features:
1. set caret to start of current conflict when using command: `Solve nearest conflict`
    caret must be moved because it's quite logical: i can move around the conflict and analyze.
2. make dialog menu narrower and move it to the right of the screen (not supported by API? we have only `DMENU_CENTERED`).
    menu dialog is quite big (especially with high DPI) and it covers the conflict, user can't see anything!

what options do we have to move dialog menu out of center?
maybe use something else? not dlg_menu?

...
thinking about using "validate" panel.
but when i press Enter inside validate panel, this event is not fired:
_* on_output_nav(self, ed_self, text, tag): Called on **clicking** line, or pressing **Enter**, in the Output or **Validate** panel. Param "text" is clicked line, param "tag" is int value associated with line._

and clicking on line in validate panel is also not working, only double-clicking works. (but i can apparently use 
PROC_GET_VALIDATE_FORM+on_key_down)

...
maybe it's better not to change old command, but create new command that will use validate panel to quickly solve all conflicts one by one using "1", "2", "3" keys, for example.

**Comment by Alexey-T** [comment]
>what options do we have to move dialog menu out of center?

nothing. all DMENU_xx are listed in docs.

>maybe use something else? not dlg_menu?

then it will look not 'usual'. consider to only reduce the `w` of the dialog (param `w=`).

**Comment by Alexey-T** [comment]
>Called on clicking line, 

Docs say wrong: it is called only on DBL-clicking. Fixed in wiki.

**Comment by Alexey-T** [comment]
my test shows that DBL-click in validate panel - calls on_output_nav. no?

**Comment by Alexey-T** [comment]
about hotkeys 1 / 2 / 3 - bad idea IMHO. why? it is very detailed work to solve conflicts in git. not such fast key press.

**Comment by veksha** [comment]
> about hotkeys 1 / 2 / 3 - bad idea IMHO. why? it is very detailed work to solve conflicts in git. not such fast key press.

agree. not intuitive for new users and to much work to implement.

> my test shows that DBL-click in validate panel - calls on_output_nav. no?

yes. wiki says that it works for Output and Validate. I don't know if Enter key works for Output, but not working for Validate for sure.

> then it will look not 'usual'. consider to only reduce the w of the dialog (param w=).

ok. let's reduce `w`? to what value? (and maybe `h`?)

> 1. set caret to start of current conflict when using command: `Solve nearest conflict`

agree on this?

**Comment by Alexey-T** [comment]
>I don't know if Enter key works for Output, but not working for Validate for sure.

worked before (in old version), broken it when reworking.
added Enter handling now. ok?

>ok. let's reduce w? to what value? (and maybe h?)

I dont know. it is your idea...

>set caret to start of current conflict when using command: Solve nearest conflict== agree on this?

yes

**Comment by veksha** [comment]
> > I don't know if Enter key works for Output, but not working for Validate for sure.
> 
> worked before (in old version), broken it when reworking. added Enter handling now. ok?

yes. nice.

PR: https://github.com/CudaText-addons/cuda_git_conflict/pull/1

**Comment by CudaText-addons** [comment]
applied. I cannot close the issue, pls close
